# Generated by Django 3.0.5 on 2020-04-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(null=True, upload_to='static/character_portraits'),
        ),
    ]
