# Generated by Django 3.0.5 on 2020-04-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20200408_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(null=True, upload_to='character_portraits'),
        ),
    ]
