# Generated by Django 3.0.5 on 2020-04-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200408_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='postname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='prename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
