# Generated by Django 3.0.5 on 2020-04-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20200409_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='postname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='prename',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
