# Generated by Django 3.0.5 on 2020-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20200414_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='party',
            field=models.BooleanField(null=True),
        ),
    ]
